python = "3.12"

[cuda]
packages = ["flash-attn", "sageattention", "torch-scatter", "torch-cluster", "spconv", "cumm"]

[pypi-dependencies]
trimesh = "*"
diffusers = "*"
timm = "*"
einops = "*"
numpy = ">=1.20.0"
scipy = "*"
scikit-learn = "*"
scikit-image = "*"
fpsample = "==0.3.2"
addict = "*"
omegaconf = "*"
huggingface-hub = "*"
hf-transfer = "*"
Pillow = "*"
tqdm = "*"
pccm = "*"
hf_xet = "*"
psutil = "*"
comfy-aimdo = "*"

[target.win-64.pypi-dependencies]
pymeshlab = "==2023.12.post3"

[target.linux-64.dependencies]
pymeshlab = "==2023.12.post3"